### ISSUE TITLE
Question: why are @available directives commented out?

### ISSUE THREAD

**Issue by BasThomas** [apple/swift-system#3]
Like e.g. here: https://github.com/apple/swift-system/blob/8ffa04c0a0592e6f4f9c30926dedd8fa1c5371f9/Sources/System/FileDescriptor.swift#L17

Are these supposed to be commented out, and if so, why?

**Comment by Snowy1803** [comment]
I’d guess System was supposed to be included in those versions of the OSes, but then they decided to make it an open source Swift Package, compatible with Linux

**Comment by milseman** [comment]
This is due to language/tooling issues. We'd like the ability to add availability based on conditional compilation for ABI-stable builds of Swift System while not adding availability for package builds (i.e. a source dependency). For now, we include, but comment out, the availability declarations matching what has already been shipped in binary releases.

**Comment by stephentyrone** [comment]
@Snowy1803 Note that System _is_ included in those versions of the OSes (https://developer.apple.com/documentation/system).

**Comment by BasThomas** [comment]
Would it help to add an explanation to it somewhere, either in comment(s) or in the documentation?

**Comment by milseman** [comment]
@BasThomas definitely. I'm trying to put together some more extensive documentation and this should be part of that.

**Comment by milseman** [comment]
I put this in the new FAQ issue: https://github.com/apple/swift-system/issues/18

**Comment by BasThomas** [comment]
Great!
